### ISSUE TITLE
Rounding factors to 3 decimal places leaves only 1 sig fig for N2O factors

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/supply-chain-factors#22]

**Comment by WesIngwersen** [comment]
Possible solutions are using scientific notation for just N2O or for all gases, or a customized number of digits per gas.

**Comment by MoLi7** [comment]
It makes more sense to me to have the same form of factors for all factors.

Here is a possible solution to give users freedom to 1) choose between scientific notation and decimal form and 2) customize number of digits for decimal form.


https://user-images.githubusercontent.com/28787399/166995850-c4ad8abd-b4f0-4d60-bd74-6ea01ef752b1.mov
