### ISSUE TITLE
Error generating factors for industry model

### ISSUE THREAD

**Issue by bl-young** [USEPA/supply-chain-factors#47]
```{R}
# Calculate margin impacts for M and N matrices
model <- c(model, calculateMarginSectorImpacts(model))

Error in margins_by_sector[gsub("/.*", "", colnames(A_margin)), gsub("/.*",  : 
  subscript out of bounds
```
_Originally posted by @TheoC-ERM in https://github.com/USEPA/supply-chain-factors/discussions/42#discussioncomment-5925237_

**Comment by WesIngwersen** [comment]
The [recent update in useeior](https://github.com/USEPA/useeior/commit/66dd2514da6cba0d7eabb5e24f7948bfd881ad00) will allow for this function to be run with an industry-based model. That update is in the master branch of useeior. But note the code here will not integrate that if run as is. you would need to skip these lines (20-21) and install useeior from master and then execute.
```
SEFversion <- get_latest_SEF_version()
install_useeior(SEFversion)
```
A Disclaimer here is that we did not provide an industry model spec file and didn't therefore fully evaluate one, so industry model set of factors with that understanding

**Comment by shwetahmehta** [comment]
Tried doing the above and got the following error. 

![Screenshot 2023-06-09 at 2 53 55 PM](https://github.com/USEPA/supply-chain-factors/assets/8670956/89ac13a8-c0cc-44f6-b23b-a3de040c85e8)

**Comment by bl-young** [comment]
Hi @shwetahmehta, see this [commit](https://github.com/USEPA/supply-chain-factors/commit/501d798810596e5a95f197039183ae4ecb16fa30) on the dev branch. Let me know if that doesn't resolve it for you.
